export const PUBLIC_KEY = `
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAz45rFETf+bVmKabOH426
OtkNZmLI8RUFpEEnAkA2gK//1Kq/Nvbuztjgts9rXpZYs1F10HJtlXwIP6z3ISve
yETikjoNbhX0bXPXl26b+yWbomCohYLfSkxXGPok4SeM/StVlVvKUXeyEF0YvH5m
ASY5qhp3gjmG1sFhtu/SwWKGj9AA+1+dHTyvwhqCgFYDen2+QgixnFxmgRx9Yp6d
Tjnzg36i3M6KeXySNweXsA3BkF6gD6v2HezLLjydUnVsAx6vDebtuRzHSPCHSRoW
ni8XfcpBLIbmzIMKRz8xqaZb2PtlPHvMdXTzwTlKRl1AUVGWmRgZvycQvNkFWYA3
MwIDAQAB
-----END PUBLIC KEY-----
`